TrailSquad/wiredexam-react-app

src/App.js, src/Cover/ReportCorver.jsx
* feat: cover
* feat: cover
* feat: rename
* feat: rename
Co-authored-by: tianyang <tianyang.zhao@wiredcraft.com>
=> Feat/dev cover (#10)

.github/workflows/build.yml
1. 将 https://github.com/tanwanimohit/deploy-react-to-ghpages/blob/master/action.yml 中的内容粘了过来
2. 修改`npm i`为`npm i -f`，避免peerDependency冲突导致安装失败
=> feat: custom steps, use npm i force

src/App.js, src/components/Location/index.jsx, src/components/MemoryLeak/index.jsx, src/components/PdfDocument/index.js
=> feat: render location use data

src/App.js, src/components/FPS/index.js, src/mock/fps.json, src/pdfStyles.js, src/utils/getChartsBlobImage.js
=> feat: fps ui

src/App.js, src/components/NetAbstract/index.jsx, src/mock/network.json, src/pdfStyles.js
- existing `sectionsTitle` for section title
- existing `text` for title
- `tableTitle` for table title
- `tableRowLabel`, `tableRowValue` for table item
=> feat: add mock network data and update network style

src/components/Cover/index.js, src/components/FPS/index.js, src/components/LaunchTime/index.jsx, src/components/Location/index.jsx, src/components/MemoryLeak/index.jsx, src/components/NetAbstract/index.jsx, src/components/PdfDocument/index.js, src/pdfStyles.js
- update copy for network
- use `contentContainer` for each section
- use `tableContainer` for table
- add table header
- only one row in table
[sample.pdf](https://github.com/TrailSquad/wiredexam-react-app/files/10895911/document.12.pdf)
=> feat: update network style and copy

src/App.js, src/components/Cover/index.js, src/components/FPS/index.js, src/pdfStyles.js
fps perfection
- update fps description
- add indicators table
- add pie chart
- add chart explanation
- add data source descript
ion
=> feat: fps perfection

src/components/FPS/index.js, src/components/LaunchTime/index.jsx, src/components/PowerUsageChart/index.jsx
- fps and launch time chart x-axis update
- update power usage pie chart to table
=> feat: update chart and table

src/App.js, src/components/Contents/index.js, src/components/LaunchTime/index.jsx, src/components/MemoryLeak/index.jsx, src/components/PdfDocument/index.js, src/components/PowerUsageChart/index.jsx
- content page section auto index
=> feat: auto content page index

src/components/PdfDocument/index.js
=> fix: fix err

src/App.js, src/components/BackCover/index.js, src/components/Cover/index.js, src/components/PdfDocument/index.js, src/mock/fps.json, src/mock/memoryLeak.json
=> feat: fix err

src/pdfStyles.js
=> feat: add bgcolor for chart

src/components/FPS/index.js, src/components/LaunchTime/index.jsx, src/components/PowerUsageChart/index.jsx, src/pdfStyles.js
- add box and break for chart bg
=> fix: add box and break for chart bg

src/components/FPS/index.js, src/components/LaunchTime/index.jsx, src/components/MemoryLeak/index.jsx, src/components/PowerUsageChart/index.jsx, src/constants/index.js, src/constants/strings.js
1. Updated the section description with chatGPT
2. Moved some strings into the contents folder
=> chore: update section descriptions

src/components/Conclusion/index.jsx, src/components/LaunchTime/index.jsx, src/constants/strings.js, src/utils/grade.js
ticket ref: https://wiredcraft.atlassian.net/browse/MOB-361
- add launchTime standard Link
=> feat: add launchTime standard Link

src/components/Conclusion/index.jsx, src/constants/strings.js
ticket ref: https://wiredcraft.atlassian.net/browse/MOB-362
- add network standard links
=> feat: add network standard links

src/components/Contents/index.js
ticket: https://wiredcraft.atlassian.net/browse/MOB-391
- fix content
=> fix: content

src/App.js, src/components/MemoryLeak/index.jsx
ticket: https://wiredcraft.atlassian.net/browse/MOB-409
- fix memory leak subtitle
=> fix: fix memory leak subtitle

src/App.js, src/components/ANR/index.jsx, src/components/Conclusion/index.jsx, src/components/Contents/index.js, src/components/PdfDocument/index.js, src/constants/strings.js, src/mock/jank.json
ticket: https://wiredcraft.atlassian.net/browse/MOB-388
- add jank data
=> feat: jank ANR

src/components/PdfDocument/index.js
=> fix: backCover

src/components/Conclusion/index.jsx, src/components/PdfDocument/index.js, src/components/UIResponse/index.jsx, src/constants/directories.js, src/constants/strings.js
ticket: https://wiredcraft.atlassian.net/browse/MOB-454
- fix description
- rename to UIResponse
=> fix: fix description
